### ISSUE TITLE
spr diff vs spr diff --draft

### ISSUE THREAD

**Issue by Coobaha** [getcord/spr#148]
Hi, I've noticed one edge case (or at least behavior that I think should be different):

1. `spr diff`
2. convert PR to draft from GitHub UI
3. git amend
4. `spr diff`

In this case, I've got a new PR created. Should the already existing draft PR be re-used?

**Comment by Coobaha** [comment]
Not sure if my repro here is correct. Doing these steps works fine for me. Something else probably resulted in a new PR, closing for now.

**Comment by Coobaha** [comment]
Ok found the way where flow fails.
if PR was manually converted to Draft from UI, next call to spr diff will create a duplicate

**Comment by sven-of-cord** [comment]
That still shouldn't happen though. The sole criterion whether spr creates a new PR or updates an existing one, is whether the commit message has a `Pull Request:` section in it with a link to the PR (within the given GitHub repository).
