### ISSUE TITLE
spr diff does not work after rebasing

### ISSUE THREAD

**Issue by opqpop** [getcord/spr#149]
i tried rebasing and now `spr diff` doesnt work, it keeps creating a brand new PR, 

could you help check where i did wrong following steps in https://getcord.github.io/spr/user/simple.html#conflicts-on-landing?

- git checkout origin/main
- touch code.py
- add and stage code.py, then git commit -m "changes"
- spr diff, PR is created, branch `origin/spr/opqpop/dracuieasy-split-solid-liquid-investments` is created (0501d416)
- wait 2 days
- PR is accepted, now i have to land but master has moved too much and i need to rebase

<img width="956" alt="image" src="https://user-images.githubusercontent.com/5566843/199621773-e1baec9a-766b-44b8-9cb8-1c1149b07f95.png">

1. git checkout origin/spr/opqpop/dracuieasy-split-solid-liquid-investments
2. git rebase origin/main
3. now the rebase replays it with new commit hashes and the branch name is no longer there, believe this is expected (see a5435a3e)
4. normally if i wasnt using spr, i'd force push my PR, but instructions say to run `spr diff` again after rebasing to update the PR
5. i do that and it ends up creating a new PR w/ the name origin/spr/opqpop/-initial-version instead

am i missing something in step 4? Do I need to do something after rebasing before calling `spr diff` again, or did I mess up the rebase command in step 2?

<img width="951" alt="image" src="https://user-images.githubusercontent.com/5566843/199622035-1ec3411a-5232-4b36-a634-4bb1d35ab1e7.png">

instructions say to rebase but doesnt say how so I wasnt sure
```
Rebase your PR onto latest upstream main, resolving conflicts in the process.
Run spr diff to update the PR
```

**Comment by sven-of-cord** [comment]
When you run `spr diff` it injects a line into the commit message that begins with "Pull Request:" and contains the URL of the Pull Request on GitHub.

You must preserve this line in order to make updates to this PR!

If you remove this line from your local commit message, `spr diff` will create a new PR next time.

Whenever you run `spr diff` it checks first if the local commit message has a "Pull Request:" line. If yes, it updates the referenced PR, if no it creates a new one.

**Comment by sven-of-cord** [comment]
There is a slight mistake in your workflow:

> 1. git checkout origin/spr/opqpop/dracuieasy-split-solid-liquid-investments

You shouldn't checkout the branch that spr created on GitHub, but your local branch that has the commit in it that you originally submitted using spr. Your old, original commit is the one you need to rebase onto current master and then resubmit with `spr diff`.

When you run `spr diff` the first time, spr injects one line into your local commit message beginning with "Pull Request:". Now you can amend and/or rebase that commit and call `spr diff` again to update on GitHub. When `spr diff` is run on a commit which has the "Pull Request:" line in the commit message, it updates an existing commit.

spr does create those `spr/opgpop/...` branches on GitHub. Please ignore those completely. Never check them out. Those branches are what spr prepares under-the-hood to translate changes of your local commit to a branch GitHub understands. You just keep working with your original commit on your local branch.
