### ISSUE TITLE
`spr init` should validate the provided branchPrefix

### ISSUE THREAD

**Issue by AdarLieberDembo-at** [getcord/spr#152]
As the branchPrefix will be part of the refname, it should be validated against the criteria found in the [git check-ref-format manpage](https://git-scm.com/docs/git-check-ref-format). Otherwise `spr diff` can fail like this:
```
fatal: invalid refspec '40cf956ffd653ba646b24d0fef9cb1696300babb:refs/heads/spr/someUser/[bad branchPrefix]/some-commit-summary'
  �  git push failed
```

**Comment by cadolphs** [comment]
I thought this was a reasonably straightforward issue to dive in and get my hands dirty. Love the idea behind the `spr` tool and even better that it's written in Rust :)
